### ISSUE TITLE
ERROR nextflow.extension.OperatorImpl - @unknown

### ISSUE THREAD

**Issue by huipan1973** [iraiosub/riboseq-flow#88]
Hi,

I setup Riboseq-flow using NextFlow and Singularity which are installed in a Conda environment. I can run the test without errors.

nextflow run iraiosub/riboseq-flow -r v1.1.1 -resume -profile test,singularity  -> passed
nextflow run iraiosub/riboseq-flow -r v1.1.1 -resume -profile full_test,singularity  -> passed

However, when I run the pipeline with real data, I get an error. The command I use is:

nextflow run iraiosub/riboseq-flow -r v1.1.1 -resume -profile singularity,crick --input /n/jobspace/bbcore/schaffer_rpf_abby_min6/riboseq_flow/samplesheet.csv --with_umi --umi_extract_method regex --umi_pattern '"^(?P<umi_1>.{2}).+(?P<umi_2>.{5})(?P<cell_1>.{5})AGATCGGAAGAGCAC{s<=2}.*"' --adapter_threeprime AGATCGGAAGAGCAC --minimum_quality 20 --strandedness reverse --expected_length '18:60' --org GRCm39 --outdir results_abby_rpf

The error message:

ERROR nextflow.extension.OperatorImpl - @unknown
java.lang.IllegalArgumentException: Argument of `file` function cannot be null
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.Nextflow.file(Nextflow.groovy:110)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at Script_fd903a43cf11ba85$_runScript_closure1.doCall(Script_fd903a43cf11ba85:17)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
	at nextflow.extension.MapOp$_apply_closure1.doCall(MapOp.groovy:56)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1007)
	at groovy.lang.Closure.call(Closure.java:433)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
	at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
	at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
	at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
	at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
	at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
	at java.base/java.util.concurrent.ThreadPerTaskExecutor$TaskRunner.run(ThreadPerTaskExecutor.java:314)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Jun-22 06:13:55.828 [Actor Thread 101] DEBUG nextflow.Session - Session aborted -- Cause: Argument of `file` function cannot be null

**Comment by huipan1973** [comment]
I fixed it. It was because of the format of CVS sample sheet. After I removed the quotes around the strings, everything worked as expected. Please forgive me for being a new user of Nextflow and asking so many trivial questions.

**Comment by iraiosub** [comment]
Hi Hui,

Glad riboseq-flow worked for you. If you found the pipeline helpful, consider starring it on GitHub! This helps others discover our work and supports the continued development of the project.

Thank you for your support!
